# Generated by Django 4.2.16 on 2025-04-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_tbl_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Email', models.EmailField(max_length=90, null=True)),
                ('Description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_help',
        ),
    ]
