# Generated by Django 4.2.16 on 2025-04-05 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_helpdesk'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='help',
            new_name='tbl_help',
        ),
        migrations.RenameModel(
            old_name='helpdesk',
            new_name='tbl_helpdesk',
        ),
    ]
