# Generated by Django 4.2.16 on 2025-04-06 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_rename_help_tbl_help_rename_helpdesk_tbl_helpdesk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_helpdesk',
        ),
    ]
