# Generated by Django 4.2.16 on 2025-04-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_delete_tbl_helpdesk'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_courses',
            name='pdf',
            field=models.FileField(null=True, upload_to='static/doc'),
        ),
    ]
