# Generated by Django 4.2.16 on 2025-05-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_tbl_help_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('event', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tbl_faculty',
            name='mobile',
        ),
        migrations.AlterField(
            model_name='tbl_faculty',
            name='specialization',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
